# Generated by Django 4.2.19 on 2025-02-27 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الشركة")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز الشركة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shipping_companies/logos/",
                        verbose_name="الشعار",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, null=True, verbose_name="الموقع الإلكتروني"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="وصف"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "شركة شحن",
                "verbose_name_plural": "شركات الشحن",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingCompanyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="اسم الحساب")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("domestic", "شحن داخلي"),
                            ("international", "شحن دولي"),
                            ("specific_country", "دولة محددة"),
                        ],
                        max_length=20,
                        verbose_name="نوع الحساب",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="مفتاح API"
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="سر API"
                    ),
                ),
                (
                    "passkey",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="كلمة المرور",
                    ),
                ),
                ("api_base_url", models.URLField(verbose_name="رابط API الأساسي")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "specific_countries",
                    models.JSONField(
                        blank=True, null=True, verbose_name="الدول المحددة"
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="معرف العميل",
                    ),
                ),
                (
                    "warehouse_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="معرف المستودع",
                    ),
                ),
                (
                    "additional_settings",
                    models.JSONField(
                        blank=True, null=True, verbose_name="إعدادات إضافية"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="shippers.shippingcompany",
                        verbose_name="شركة الشحن",
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب شركة شحن",
                "verbose_name_plural": "حسابات شركات الشحن",
                "ordering": ["company__name", "title"],
            },
        ),
    ]
