# Generated by Django 4.2.19 on 2025-03-03 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSKUMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="معرف المنتج"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="اسم المنتج"),
                ),
                (
                    "sku_internal",
                    models.CharField(max_length=100, verbose_name="SKU الداخلي"),
                ),
                (
                    "sku_smsa_ksa",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="SKU SMSA السعودية",
                    ),
                ),
                (
                    "sku_smsa_uae",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="SKU SMSA الإمارات",
                    ),
                ),
                (
                    "sku_smsa_jordan",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="SKU SMSA الأردن",
                    ),
                ),
                (
                    "sku_naqel",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="SKU ناقل"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
            ],
            options={
                "verbose_name": "ربط SKU منتج",
                "verbose_name_plural": "ربط SKUs المنتجات",
                "indexes": [
                    models.Index(
                        fields=["product_id"], name="shippers_pr_product_5cf555_idx"
                    ),
                    models.Index(
                        fields=["sku_internal"], name="shippers_pr_sku_int_552c72_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WarehouseMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(max_length=10, verbose_name="كود الدولة"),
                ),
                (
                    "country_name",
                    models.CharField(max_length=100, verbose_name="اسم الدولة"),
                ),
                (
                    "warehouse_id",
                    models.CharField(max_length=100, verbose_name="معرف المستودع"),
                ),
                (
                    "warehouse_name",
                    models.CharField(max_length=255, verbose_name="اسم المستودع"),
                ),
                (
                    "is_domestic",
                    models.BooleanField(default=False, verbose_name="شحن داخلي"),
                ),
                (
                    "is_cargo",
                    models.BooleanField(default=False, verbose_name="شحن بضائع"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "shipping_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to="shippers.shippingcompany",
                        verbose_name="شركة الشحن",
                    ),
                ),
            ],
            options={
                "verbose_name": "ربط مستودع",
                "verbose_name_plural": "ربط المستودعات",
                "unique_together": {
                    ("shipping_company", "country_code", "warehouse_id")
                },
            },
        ),
    ]
