"""
Django settings for unifarma_shipping project.

Generated by 'django-admin startproject' using Django 4.2.19.
"""

import os
from pathlib import Path
import environ

# القراءة من ملف .env
env = environ.Env(
    DEBUG=(bool, True),
    DATABASE_ENGINE=(str, 'django.db.backends.sqlite3'),
    DATABASE_NAME=(str, 'db.sqlite3'),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
    REDIS_URL=(str, 'redis://localhost:6379/0'),
)

# إذا كان ملف .env موجودًا، استخدمه
env_file = os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env')
if os.path.exists(env_file):
    environ.Env.read_env(env_file)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# إعدادات أساسية
SECRET_KEY = env('SECRET_KEY', default='django-insecure-key-for-development-only')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

# تهيئة قاعدة البيانات
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, env('DATABASE_NAME')),
    }
}

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # تطبيقات خارجية
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'django_celery_beat',
    'django_filters',

    # تطبيقاتنا
    'core',
    'accounts',
    'crm_integration',
    'shippers',
    'orders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # لإدارة CORS
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "unifarma_shipping.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "unifarma_shipping.wsgi.application"

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Celery والمهام المجدولة
CELERY_BROKER_URL = env('REDIS_URL')
CELERY_RESULT_BACKEND = env('REDIS_URL')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

# إعدادات CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# المتغيرات الخاصة بالتطبيق
CITRIX_API_BASE_URL = env('CITRIX_API_BASE_URL', default='https://citrix-api-url.com/api')
CITRIX_API_KEY = env('CITRIX_API_KEY', default='your-citrix-api-key')

# Bitrix24 API URLs
BITRIX_DEAL_FIELDS_URL = env('BITRIX_DEAL_FIELDS_URL', default='https://unifarma.bitrix24.com/rest/1/xe6q61jh4s1mjfp2/crm.deal.fields.json')
BITRIX_DEAL_LIST_URL = env('BITRIX_DEAL_LIST_URL', default='https://unifarma.bitrix24.com/rest/1/pt1calillkfnrmlx/crm.deal.list.json')
BITRIX_DEAL_GET_BASE_URL = env('BITRIX_DEAL_GET_BASE_URL', default='https://unifarma.bitrix24.com/rest/1/ndnsgn65rr6czcsw/crm.deal.get.json')
BITRIX_DEAL_PRODUCT_ROWS_URL = env('BITRIX_DEAL_PRODUCT_ROWS_URL', default='https://unifarma.bitrix24.com/rest/1/jyi1o07uubaikfmw/crm.deal.productrows.get.json')
BITRIX_DEAL_CONTACT_ITEMS_URL = env('BITRIX_DEAL_CONTACT_ITEMS_URL', default='https://unifarma.bitrix24.com/rest/1/hpf5ak4s823kx74o/crm.deal.contact.items.get.json')
BITRIX_CONTACT_GET_URL = env('BITRIX_CONTACT_GET_URL', default='https://unifarma.bitrix24.com/rest/1/jovzk7c8xp49dw3j/crm.contact.get.json')
BITRIX_USER_GET_URL = env('BITRIX_USER_GET_URL', default='https://unifarma.bitrix24.com/rest/1/q6l783iy9u00j8s1/user.get.json')
BITRIX_STAGE_LIST_URL = env('BITRIX_STAGE_LIST_URL', default='https://unifarma.bitrix24.com/rest/54/qlh6n2d7ehfz2zlg/crm.dealcategory.stage.list.json')

# SMSA API Settings
SMSA_API_BASE_URL = env('SMSA_API_BASE_URL', default='https://sam.smsaexpress.com/STAXRestApi/api')
SMSA_PASSKEY = env('SMSA_PASSKEY', default='DIQ@10077')

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"