# Generated by Django 4.2.19 on 2025-02-27 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shippers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMAPICall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[
                            ("get_deals", "جلب الصفقات"),
                            ("get_deal", "جلب صفقة"),
                            ("update_deal", "تحديث صفقة"),
                            ("other", "أخرى"),
                        ],
                        max_length=50,
                        verbose_name="نوع الطلب",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(max_length=255, verbose_name="نقطة النهاية"),
                ),
                (
                    "parameters",
                    models.JSONField(blank=True, null=True, verbose_name="المعلمات"),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="بيانات الطلب"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="بيانات الاستجابة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("success", "نجاح"),
                            ("error", "خطأ"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="رمز الحالة HTTP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="رسالة الخطأ"),
                ),
            ],
            options={
                "verbose_name": "طلب CRM API",
                "verbose_name_plural": "طلبات CRM API",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRMDealStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="معرف المرحلة"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المرحلة")),
                (
                    "is_shipping_stage",
                    models.BooleanField(default=False, verbose_name="مرحلة شحن"),
                ),
            ],
            options={
                "verbose_name": "مرحلة صفقة CRM",
                "verbose_name_plural": "مراحل صفقات CRM",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CRMWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("deal_update", "تحديث صفقة"),
                            ("deal_create", "إنشاء صفقة"),
                            ("deal_delete", "حذف صفقة"),
                            ("other", "أخرى"),
                        ],
                        max_length=50,
                        verbose_name="نوع الحدث",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="معرف الحدث"
                    ),
                ),
                ("payload", models.JSONField(verbose_name="بيانات الحدث")),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="تمت المعالجة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ المعالجة"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد محاولات إعادة المعالجة"
                    ),
                ),
            ],
            options={
                "verbose_name": "حدث CRM Webhook",
                "verbose_name_plural": "أحداث CRM Webhook",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRMShippingMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crm_field", models.CharField(max_length=100, verbose_name="حقل CRM")),
                (
                    "crm_value",
                    models.CharField(max_length=100, verbose_name="قيمة CRM"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "shipping_company_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shippers.shippingcompanyaccount",
                        verbose_name="حساب شركة الشحن",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعيين شحن CRM",
                "verbose_name_plural": "تعيينات شحن CRM",
                "ordering": ["crm_field", "crm_value"],
                "unique_together": {("crm_field", "crm_value")},
            },
        ),
    ]
