# Generated by Django 4.2.19 on 2025-02-27 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shippers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "citrix_deal_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="معرف الصفقة في سيتريكس",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("processing", "قيد المعالجة"),
                            ("shipped", "تم الشحن"),
                            ("delivered", "تم التسليم"),
                            ("cancelled", "ملغي"),
                            ("returned", "مرتجع"),
                            ("error", "خطأ"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="اسم العميل"),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="هاتف العميل"
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="بريد العميل الإلكتروني",
                    ),
                ),
                (
                    "shipping_country",
                    models.CharField(max_length=100, verbose_name="دولة الشحن"),
                ),
                (
                    "shipping_city",
                    models.CharField(max_length=100, verbose_name="مدينة الشحن"),
                ),
                ("shipping_address", models.TextField(verbose_name="عنوان الشحن")),
                (
                    "shipping_postal_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="الرمز البريدي",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ الإجمالي"
                    ),
                ),
                (
                    "cod_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="مبلغ الدفع عند الاستلام",
                    ),
                ),
                (
                    "is_cod",
                    models.BooleanField(default=False, verbose_name="دفع عند الاستلام"),
                ),
                (
                    "citrix_created_at",
                    models.DateTimeField(verbose_name="تاريخ الإنشاء في سيتريكس"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء في النظام"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الشحن"
                    ),
                ),
                (
                    "citrix_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="بيانات سيتريكس الأصلية"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "shipping_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="shippers.shippingcompanyaccount",
                        verbose_name="حساب الشحن",
                    ),
                ),
                (
                    "shipping_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="shippers.shippingcompany",
                        verbose_name="شركة الشحن",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب",
                "verbose_name_plural": "الطلبات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="رقم التتبع"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("submitted", "تم الإرسال"),
                            ("accepted", "تم القبول"),
                            ("in_transit", "في الطريق"),
                            ("delivered", "تم التسليم"),
                            ("returned", "مرتجع"),
                            ("cancelled", "ملغي"),
                            ("error", "خطأ"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإرسال"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التسليم"
                    ),
                ),
                (
                    "shipping_company_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="استجابة شركة الشحن"
                    ),
                ),
                (
                    "events_log",
                    models.JSONField(blank=True, null=True, verbose_name="سجل الأحداث"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "shipping_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="shippers.shippingcompanyaccount",
                        verbose_name="حساب الشحن",
                    ),
                ),
                (
                    "shipping_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="shippers.shippingcompany",
                        verbose_name="شركة الشحن",
                    ),
                ),
            ],
            options={
                "verbose_name": "شحنة",
                "verbose_name_plural": "الشحنات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(max_length=100, verbose_name="معرف المنتج"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="اسم المنتج"),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="رمز المنتج"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="الكمية"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر الإجمالي"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="الوزن (كجم)",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="رقم الدفعة"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="الرقم التسلسلي",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "citrix_item_data",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="بيانات عنصر سيتريكس الأصلية",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر طلب",
                "verbose_name_plural": "عناصر الطلبات",
                "ordering": ["order", "id"],
            },
        ),
    ]
